# Generated by Django 5.1.4 on 2025-01-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="friend_requests",
            field=models.ManyToManyField(
                blank=True, related_name="pending_requests", to="core.profile"
            ),
        ),
    ]
