# Generated by Django 5.1.4 on 2025-01-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_profile_birthdate_profile_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="profile_pictures/default.png",
                null=True,
                upload_to="profile_pictures/",
            ),
        ),
    ]
